spring.application.name=studylist
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:~/taskdb

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.sql.init.mode=always
spring.h2.console.enabled=true